config/routes.rb
Rails.application.routes.draw do
  resources :categories, :quotes

  root to: "categories#index"

  get "/politicians", to: redirect("categories/1")
  get "/actors", to: redirect("categories/2")

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :quotes
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	belongs_to :category
	validates :string, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

def show
	@quotes = Quote.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/categories/index.html.erb
<h1>Quote Categories</h1>

<ul>
	<% @categories.each do |category| %>
	<li><%= link_to category.name, category %></li>
	<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
	<% @category.quotes.each do |quote| %>
	<li><%= link_to quote.string, quote %></li>
	<% end %>
</ul>

<p><%= link_to "Back to Quote Categories", categories_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotesforfree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/show.html.erb
<h1><%= @quote.name %></h1>
<p><%= @quote.string %></p>

<% if @quote.category_id == 1 %>
<p><%= link_to "Back to Quotes from Politicians", politicians_path %></p>
<% end %>

<% if @quote.category_id == 2 %>
<p><%= link_to "Back to Quotes from Actors", actors_path %></p>
<% end %>